-keep public class org.matheclipse.core.** {*; }
-keep interface org.matheclipse.core.interfaces.IPattern
-keep android.webkit.SafeBrowsingResponse
-keep android.webkit.RenderProcessGoneDetail
-keep org.apache.** {*;}